Repository btovis/btovis.github.io, pull requests merged in 2024-03, with the labels that each got.

#235 Merge Line Chart and Stacked Line Chart
  devfiles/src/classes/options/Selector.tsx
  devfiles/src/classes/widgets/LineChart.tsx
  devfiles/src/classes/widgets/StackedLineChart.tsx
  devfiles/src/classes/widgets/TimeChart.tsx
  devfiles/src/ui/PanelComp.tsx
Labels: ui

#236 Group by English name
  devfiles/src/classes/widgets/Grouping.test.ts
  devfiles/src/classes/widgets/Grouping.ts
Labels: ui

#244 Add warning message when user tries to leave with unsaved data
  devfiles/src/App.tsx
Labels: ui

#242 Vulnerability
  devfiles/src/classes/data/Data.ts
  devfiles/src/classes/widgets/Grouping.ts
Labels: tweak, refactor

#246 Species selector polish
  devfiles/src/App.css
  devfiles/src/classes/options/DateRange.tsx
  devfiles/src/classes/options/Geographic.tsx
  devfiles/src/classes/options/MutuallyExclusiveSelector.tsx
  devfiles/src/classes/options/NumericInput.tsx
  devfiles/src/classes/options/Selector.tsx
  devfiles/src/classes/options/SpeciesSelector.tsx
  devfiles/src/classes/options/TimeOfDayRange.tsx
  devfiles/src/classes/widgets/MapWidget.tsx
Labels: ui

#252 Get rid of unused code
  .eslintrc.cjs
  devfiles/src/App.tsx
  devfiles/src/classes/Panel.ts
  devfiles/src/classes/data/Data.ts
  devfiles/src/classes/data/DataFilterer.test.ts
  devfiles/src/classes/data/DataStats.test.ts
  devfiles/src/classes/data/setutils/SetElement.ts
  devfiles/src/classes/filters/Filter.ts
  devfiles/src/classes/filters/RangeFilter.ts
  devfiles/src/classes/filters/SetFilter.ts
  devfiles/src/classes/filters/SwappableRangeFilter.ts
  devfiles/src/classes/options/ColorOption.tsx
  devfiles/src/classes/options/Geographic.tsx
  devfiles/src/classes/options/InputOption.tsx
  devfiles/src/classes/options/MutuallyExclusiveSelector.tsx
  devfiles/src/classes/options/PanelNameInput.tsx
  devfiles/src/classes/options/Selector.tsx
  devfiles/src/classes/options/SpeciesSelector.tsx
  devfiles/src/classes/options/TextInput.tsx
  devfiles/src/classes/query/SetQueryArray.ts
  devfiles/src/classes/query/SetQueryArrayReject.ts
  devfiles/src/classes/query/SetQueryElement.ts
  devfiles/src/classes/query/SetQueryGeneral.ts
  devfiles/src/classes/query/SwappableRangeQuery.ts
  devfiles/src/classes/queryMeta/SpeciesMeta.ts
  devfiles/src/classes/widgets/BarChart.tsx
  devfiles/src/classes/widgets/DebugWidget.tsx
  devfiles/src/classes/widgets/ExportFileType.ts
  devfiles/src/classes/widgets/Grouping.test.ts
  devfiles/src/classes/widgets/Grouping.ts
  devfiles/src/classes/widgets/LineChart.tsx
  devfiles/src/classes/widgets/MapWidget.tsx
  devfiles/src/classes/widgets/TableWidget.tsx
  devfiles/src/classes/widgets/TimeChart.tsx
  devfiles/src/classes/widgets/Widget.tsx
  devfiles/src/ui/OptionsComp/GlobalOptionsComp.tsx
  devfiles/src/ui/OptionsComp/InputOptionComp.tsx
  devfiles/src/ui/PanelComp.tsx
  devfiles/src/ui/SidebarComp.tsx
  devfiles/src/ui/WidgetComp.tsx
  devfiles/src/utils/DataUtils.test.ts
Labels: workflow, refactor

#245 Chart/Widget Design
  devfiles/src/App.css
  devfiles/src/classes/widgets/LineChart.tsx
  devfiles/src/classes/widgets/MapWidget.tsx
  devfiles/src/classes/widgets/TimeChart.tsx
  devfiles/src/index.css
  package.json
Labels: ui, design

#237 Widget fullscreen
  devfiles/src/App.css
  devfiles/src/App.tsx
  devfiles/src/classes/widgets/DebugWidget.tsx
  devfiles/src/classes/widgets/MapWidget.tsx
  devfiles/src/classes/widgets/TableWidget.tsx
  devfiles/src/classes/widgets/TimeChart.tsx
  devfiles/src/classes/widgets/Widget.tsx
  devfiles/src/ui/OptionsComp/PanelOptionsComp.tsx
  devfiles/src/ui/PanelComp.tsx
Labels: ui

#255 Change font sizes (and other UI tweaks)
  devfiles/src/App.css
  devfiles/src/App.tsx
  devfiles/src/assets/license.json
  devfiles/src/assets/license.txt
  devfiles/src/classes/Panel.ts
  devfiles/src/classes/options/BinarySelector.tsx
  devfiles/src/classes/options/DateRange.tsx
  devfiles/src/classes/options/Geographic.tsx
  devfiles/src/classes/options/InputOption.tsx
  devfiles/src/classes/options/NumericInput.tsx
  devfiles/src/classes/options/Selector.tsx
  devfiles/src/classes/options/SpeciesSelector.tsx
  devfiles/src/classes/options/TimeOfDayRange.tsx
  devfiles/src/classes/options/TraceOption.tsx
  devfiles/src/classes/widgets/LineChart.tsx
  devfiles/src/classes/widgets/TimeChart.tsx
  devfiles/src/ui/OptionsComp/GlobalOptionsComp.tsx
  devfiles/src/ui/OptionsComp/PanelOptionsComp.tsx
  devfiles/src/ui/PanelComp.tsx
  package-lock.json
  package.json
Labels: ui, design

#257 Finalised overlay component
  devfiles/src/App.css
  devfiles/src/App.tsx
  devfiles/src/classes/data/Data.ts
  devfiles/src/ui/ErrorOverlay.tsx
  devfiles/src/ui/SuccessOverlay.tsx
Labels: ui

#263 Fix #262
  devfiles/src/classes/options/Geographic.tsx
Labels: ui

#264 Increased widget row sensitivity
  devfiles/src/App.css
Labels: ui, design

#266 Merge CSS
  devfiles/src/App.css
  devfiles/src/index.css
  devfiles/src/main.tsx
Labels: tweak, refactor

#276 UI Tweaks
  devfiles/favicon.ico
  devfiles/src/App.css
  devfiles/src/App.tsx
  devfiles/src/classes/options/InputOption.tsx
  devfiles/src/classes/options/PanelNameInput.tsx
  devfiles/src/classes/options/SpeciesSelector.tsx
  devfiles/src/classes/widgets/Grouping.ts
  devfiles/src/classes/widgets/TableWidget.tsx
  devfiles/src/classes/widgets/TimeChart.tsx
  devfiles/src/ui/ErrorOverlay.tsx
  devfiles/src/ui/MainPage.tsx
  devfiles/src/ui/OptionsComp/GlobalOptionsComp.tsx
  devfiles/src/ui/OptionsComp/PanelOptionsComp.tsx
  devfiles/src/ui/PanelComp.tsx
Labels: ui, tweak

#284 Create favicon
  devfiles/src/assets/favicon.ico
  package-lock.json
  package.json
  vite.config.ts
Labels: bug, ui

#285 Create favicon
  devfiles/index.html
Labels: ui

#283 Widget Sizing
  devfiles/src/App.css
  devfiles/src/classes/widgets/MapWidget.tsx
  devfiles/src/classes/widgets/TableWidget.tsx
Labels: ui, tweak

#282 Disable colour options
  devfiles/src/classes/widgets/BarChart.tsx
  devfiles/src/classes/widgets/LineChart.tsx
Labels: ui

#296 Update README.md
  README.md
Labels: documentation

#320 Increase font size of tootips on map and chartr widgets
  devfiles/src/classes/widgets/MapWidget.tsx
  devfiles/src/classes/widgets/TimeChart.tsx
Labels: ui, tweak

#321 Update documentation's images and data quirks
  devfiles/src/assets/documentation.pdf
Labels: documentation

#326 Cleanup before handover
  index.html
  tsconfig.json
Labels: refactor
